### ISSUE TITLE
Offline usage of angular-devtools

### ISSUE THREAD

**Issue by dbosque** [rangle/angular-devtools#782]
_Description:_

When using angular-devtools on a pc without internet connection, the icons are all messed up.
Probably because there is a reference to https://fonts.googleapis.com/icon?family=Material+Icons.

Please support offline usage.

![unnamed](https://user-images.githubusercontent.com/19816901/118786091-c3d1b000-b891-11eb-9756-4a25511d73fe.png)

**Comment by mgechev** [comment]
That's a nice one! I'll add it to the backlog and we'll evaluate its priority relative to the other feature requests we got. Thank you for the report!

**Comment by BeGj** [comment]
Lovely tool, but unfortunately is quite broken in offline.
Please consider making a fix, or provide the icons in the extension build.

**Comment by StephenCooper** [comment]
**_Probably not a recommended approach but temporary workaround_**

If you are installing as an unpacked extension you can work around this by downloading the font files yourself manually and updating the `index.html` as follows.

Replaced 
```html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /> 
```
with
```html
<link rel="stylesheet" href="fonts.css" />
```

In `fonts.css` I copied the contents of that link but updated the src to point to a local copy of the woff2 file. 

```css
/* fallback */
@font-face {
  font-family: "Material Icons";
  font-style: normal;
  font-weight: 400;
  src: url(flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2) format("woff2");
}

.material-icons {
  font-family: "Material Icons";
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: "liga";
  -webkit-font-smoothing: antialiased;
}
```
